#!/bin/python3
import sys
import asyncio
import art

from src.database import *
from vendro import commands

def help() -> None:
    print(art.text2art('ASYNCgram'))
    print('All commands:')
    print()
    print((
        'make commands:\n'
        'make:handler - create class handler in your project\n'
        'make:filter - create class filter in your project\n'
        'make:button - create class button in your project\n'
        'make:state - create class state in your project\n'
        'make:migrate - create class table in your project\n'
    ))

def make(args: list[str]) -> None:
    make = commands.Make()

    if 'make:handler' == args[1]:
        make.handler(args[2])
    elif 'make:filter' == args[1]:
        make.filter(args[2])
    elif 'make:button' == args[1]:
        make.button(args[2])
    elif 'make:state' == args[1]:
        make.state(args[2])
    elif 'make:migrate' == args[1]:
        make.migrate(args[2])

def migrate(args: list[str]) -> None:
    migrate = commands.migrate

    if 'migrate' == args[1]:
        asyncio.run(migrate.create_table())
    elif 'migrate:drop' == args[1]:
        asyncio.run(migrate.drop_table())

def main() -> None:
    args = sys.argv

    if args[1] == 'help':
        help()

    make(args)
    migrate(args)

if __name__ == '__main__':
    main()