#!/bin/python3
import sys

from vendro import commands

def main() -> None:
    make = commands.Make()

    args = sys.argv

    if 'make:handler' == args[1]:
        make.handler(args[2])
    elif 'make:filter' == args[1]:
        make.filter(args[2])
    elif 'make:button' == args[1]:
        make.button(args[2])
    elif 'make:state' == args[1]:
        make.state(args[2])
        
if __name__ == '__main__':
    main()